In [5]:
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd

In [6]:
# FONCTION AFFICHAGE DES 3 DATAFRAMES

def fn_affichage_classements(url):
    response = requests.get(url)
    # return(response)
    if response.status_code == 200:
        # return('test')

        # je crée une variable soup surn laquelle j'applique BeautifulSoup
        # avec en paramètre url.text et je découpe avec html.parser
        soup = BeautifulSoup(response.text, 'html.parser')
        # return(soup)   

        # NOM EQUIPES
        # je recherche les noms de toutes les équipes avec la balise a et la classe affichée sur la page internet
        list_nom_equipes = soup.find_all('a', {'class': 'base-link base-link--black'})

        # je crée une boucle insérer les noms des equipes dans une liste
        list_team = []
        for ele in list_nom_equipes:
                ele = str(ele)
                # Appliquer la regex à chaque élément `ele`
                match = re.search(r'>([^<]+)<', ele)
                if match:  # Vérifier si la regex a trouvé un résultat
                    list_team.append(match.group(1).strip())
        # print(list_team)    
        
        points_equipes = soup.find_all('div', {'class': 'table-line__cell--small'})
        list_points_team = []
        for points in points_equipes:
            # print(points)
            points = str(points)
            regex_points = re.search(r'[0-9]+', points)
            # print(regex_points)
            # regex_points[0]
            # print(regex_points[0])
            list_points_team.append(regex_points[0])

        all_team = soup.find_all('div', {'class': 'table-line table-line--ranking-full table-line--ranking-scrollable'})
        list_matchs_joues = []
        list_matchs_gagnes = []
        list_matchs_nuls = []
        list_matchs_perdus = []

        for team in range(0, 14):
            for data in range(1, 5):
                if data == 1:
                    points_test = all_team[team].find_all('div', {'class': ''})[data]
                    # print(re.search(r'[0-9]+', str(points_test))[0])
                    list_matchs_joues.append(re.search(r'[0-9]+', str(points_test))[0])
                elif data == 2:
                    points_test = all_team[team].find_all('div', {'class': ''})[data]
                    # print(re.search(r'[0-9]+', str(points_test))[0])
                    list_matchs_gagnes.append(re.search(r'[0-9]+', str(points_test))[0])
                elif data == 3:
                    points_test = all_team[team].find_all('div', {'class': ''})[data]
                    # print(re.search(r'[0-9]+', str(points_test))[0])
                    list_matchs_nuls.append(re.search(r'[0-9]+', str(points_test))[0])
                else:
                    points_test = all_team[team].find_all('div', {'class': ''})[data]
                    # print(re.search(r'[0-9]+', str(points_test))[0])
                    list_matchs_perdus.append(re.search(r'[0-9]+', str(points_test))[0])

        return(display(pd.DataFrame({
                "Equipes": list_team,
                "Pts": list_points_team,
                "Matchs joués": list_matchs_joues,
                "Gagnés": list_matchs_gagnes,
                "Nuls": list_matchs_nuls,
                "Perdus": list_matchs_perdus
                })))
    else:
        print("Erreur d'url")

dico_urls = {"https://top14.lnr.fr/classement": "Classement général", "https://top14.lnr.fr/classement/domicile": "Classement domicile", "https://top14.lnr.fr/classement/exterieur": "Classement extèrieur"}
for url in dico_urls.keys():
    dico_urls[url]
    print(dico_urls[url])
    # print(url)
    fn_affichage_classements(url)

Classement général

                      Equipes Pts Matchs joués Gagnés Nuls Perdus
0       Union Bordeaux-Bègles  51           15     11    0      4
1            Stade Toulousain  51           15     10    1      4
2                   RC Toulon  48           15     10    0      5
3            Aviron Bayonnais  39           15      9    0      6
4                ASM Clermont  38           15      8    0      7
5             Stade Rochelais  36           15      8    0      7
6           Castres Olympique  35           15      8    0      7
7   Montpellier Hérault Rugby  34           15      7    0      8
8                   LOU Rugby  30           15      6    2      7
9             Section Paloise  29           15      6    0      9
10              USA Perpignan  28           15      6    0      9
11                  Racing 92  26           15      5    1      9
12       Stade Français Paris  24           15      5    0     10
13                  RC Vannes  20           15      4    0     11

Classement domicile

                      Equipes Pts Matchs joués Gagnés Nuls Perdus
0                   RC Toulon  37            8      8    0      0
1       Union Bordeaux-Bègles  32            8      7    0      1
2             Stade Rochelais  31            8      7    0      1
3            Stade Toulousain  29            7      6    0      1
4                ASM Clermont  29            7      6    0      1
5            Aviron Bayonnais  29            7      7    0      0
6           Castres Olympique  29            8      7    0      1
7             Section Paloise  27            8      6    0      2
8               USA Perpignan  26            8      6    0      2
9   Montpellier Hérault Rugby  23            7      5    0      2
10       Stade Français Paris  23            7      5    0      2
11                  LOU Rugby  19            7      4    1      2
12                  Racing 92  16            7      3    1      3
13                  RC Vannes  14            8      3    0      5

Classement extèrieur

                      Equipes Pts Matchs joués Gagnés Nuls Perdus
0            Stade Toulousain  22            8      4    1      3
1       Union Bordeaux-Bègles  19            7      4    0      3
2   Montpellier Hérault Rugby  11            8      2    0      6
3                   LOU Rugby  11            8      2    1      5
4                   RC Toulon  11            7      2    0      5
5                   Racing 92  10            8      2    0      6
6            Aviron Bayonnais  10            8      2    0      6
7                ASM Clermont   9            8      2    0      6
8           Castres Olympique   6            7      1    0      6
9                   RC Vannes   6            7      1    0      6
10            Stade Rochelais   5            7      1    0      6
11              USA Perpignan   2            7      0    0      7
12            Section Paloise   2            7      0    0      7
13       Stade Français Paris   1            8      0    0      8

# script d'upload vers S3

In [13]:
import pandas as pd

# Supposons que ton DataFrame s'appelle `df`
df.to_json("data_brute/scraping_data_classement.json", orient="records", lines=True)
print("✅ Données exportées en JSON !")

NameError: name 'df' is not defined

In [2]:
# définir le chemin d'accès absolu du notebook

import os

# Récupérer le chemin absolu
json_path = os.path.join(os.getcwd(), 'data_brute', 'scraping_data_classement.json')
print(f"Chemin local : {json_path}")

Chemin local : c:\Users\aurel\WILD_CODE_SCHOOL\GIT_PROJET_RUGBY\rugby3\data_brute\scraping_data_classement.json

In [1]:
import os
import boto3

# Définition du chemin local
json_path = os.path.join(os.getcwd(), 'data_brute', 'scraping_data_classement.json')
print(f"📂 Chemin local du fichier : {json_path}")

# Configuration AWS S3
bucket_name = "pipeline-data-brutes-classement-equipe"
s3_file = "data_brute/scraping_data_classement.json"  # Emplacement sur S3

# Initialiser le client S3
s3 = boto3.client("s3")

# Vérifier si le fichier existe avant l'upload
if os.path.exists(json_path):
    # Upload
    s3.upload_file(json_path, bucket_name, s3_file)
    print(f"✅ Fichier {json_path} uploadé sur S3 dans {bucket_name}/{s3_file}")
else:
    print(f"❌ Erreur : Le fichier {json_path} n'existe pas !")

📂 Chemin local du fichier : c:\Users\aurel\WILD_CODE_SCHOOL\GIT_PROJET_RUGBY\rugby3\data_brute\scraping_data_classement.json
❌ Erreur : Le fichier c:\Users\aurel\WILD_CODE_SCHOOL\GIT_PROJET_RUGBY\rugby3\data_brute\scraping_data_classement.json n'existe pas !

In [3]:
# pour vérifier dans quel repertoire tourne le notebook
print(os.getcwd())

c:\Users\aurel\WILD_CODE_SCHOOL\GIT_PROJET_RUGBY\rugby3

In [4]:
print(os.listdir("data_brute"))

FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'data_brute'